# Generated by Django 4.1 on 2022-08-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmiapp', '0004_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Address',
            new_name='address',
        ),
    ]
